### ISSUE TITLE
load_quandl_sf1.py did not work with zipline-reloaded

### ISSUE THREAD

**Issue by carstenf** [pbharrin/alpha-compiler#11]
I managed to ingest, see pull request, but than load_quandl_sf1.py did not work.
Th issue is this:

lifetimes = bundle_data.asset_finder._compute_asset_lifetimes(frozenset([str("US")]))
TypeError: _compute_asset_lifetimes() takes 1 positional argument but 2 were given

-----------------

(ml4t_p8) carsten@MacBook-Pro-2 ~ % python /Users/carsten/Documents/Python/My_Python_Models/ML-Factor_invest/load_quandl_sf1.py
Loading Extensions

Traceback (most recent call last):
  File "/Users/carsten/Documents/Python/My_Python_Models/ML-Factor_invest/load_quandl_sf1.py", line 219, in <module>
    num_tickers = num_tkrs_in_bundle(BUNDLE_NAME)
  File "/Users/carsten/Documents/Python/My_Python_Models/ML-Factor_invest/load_quandl_sf1.py", line 182, in num_tkrs_in_bundle
    return len(get_ticker_sid_dict_from_bundle(bundle_name))
  File "/Users/carsten/anaconda3/envs/ml4t_p8/lib/python3.8/site-packages/Alpha_Compiler-0.1-py3.8.egg/alphacompiler/util/zipline_data_tools.py", line 96, in get_ticker_sid_dict_from_bundle
    all_equities = get_tickers_from_bundle(bundle_name)
  File "/Users/carsten/anaconda3/envs/ml4t_p8/lib/python3.8/site-packages/Alpha_Compiler-0.1-py3.8.egg/alphacompiler/util/zipline_data_tools.py", line 70, in get_tickers_from_bundle
    lifetimes = bundle_data.asset_finder._compute_asset_lifetimes(frozenset([str("US")]))
TypeError: _compute_asset_lifetimes() takes 1 positional argument but 2 were given
(ml4t_p8) carsten@MacBook-Pro-2 ~ %

**Comment by pbharrin** [comment]
I remember this issue, from what I remember you need to add two arguments because the second argument needs to be "stock".  I will double check.

**Comment by pbharrin** [comment]
[See this issue](https://github.com/quantopian/zipline/issues/2517) and solution.

**Comment by carstenf** [comment]
did not saw your comment, found a solution, see my latest pull request.
old:
    #lifetimes = bundle_data.asset_finder._compute_asset_lifetimes(frozenset([str("US")]))
new:
    lifetimes = bundle_data.asset_finder._compute_asset_lifetimes(country_codes=[str("US")])

if my pull request is ok, please close the issue

PS: is this still your e-mail: peter.b.harrington@gmail.com ? try to contact you
